version: '3.8'

services:
  osticket:
    build:
      context: .
      args:
        - TIMEZONE=Europe/Copenhagen
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket
      - INSTALL_SECRET=secret
      - LANGUAGE=en
    volumes:
      - osticket:/var/www
    links:
      - mysql:mysql
    ports:
      - 8080:80

  mysql:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket

volumes:
  osticket:
